20210313 18:24:34 [36] ERROR Web [(null)] - StackTrace
   at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at Suftnet.Cos.DataAccess.OrderPayment.Insert(OrderPaymentDto entity) in E:\Git\Web\Irit\Irit\Suftnet.Cos.DataAccess\LinqtoSql\Implementation\OrderPayment.cs:line 35
   at Suftnet.Cos.Web.Command.PaymentCommand.CreatePayment() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Command\PaymentCommand.cs:line 83
   at Suftnet.Cos.Web.Command.PaymentCommand.Execute() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Command\PaymentCommand.cs:line 32
   at Suftnet.Cos.Mobile.PaymentController.<Create>b__3_0() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Controllers\Api\v1\PaymentController.cs:line 41
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Suftnet.Cos.Mobile.PaymentController.<Create>d__3.MoveNext() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Controllers\Api\v1\PaymentController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Suftnet.Cos.Web.ActionFilter.AddChallengeOnUnauthorizedResult.<ExecuteAsync>d__7.MoveNext() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Infrastructure\ActionFilter\AddChallengeOnUnauthorizedResult.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()Messages
An error occurred while updating the entries. See the inner exception for details.
--------------------------------------------
Request.Body = {"amountPaid":52.98,"createdDt":"3/13/2021 06:24:28","externalId":"115924fb-79f9-4e0c-ab5f-d4e1dfc1c893","grandTotal":52.980000000000004,"orderId":"a2bc3624-6fe9-44f0-8c27-024ed4af406c","paymentMethodId":"E0DF7037-BE71-4D90-871D-04AD8E4AD960","tableId":"2d7dcc2a-05e2-4363-bf22-ea7355d943d2","userName":"Abel James"}
--------------------------------------------
Inner Exception
Messages
An error occurred while updating the entries. See the inner exception for details.Messages
The INSERT statement conflicted with the FOREIGN KEY constraint "FK_OrderPayment_PaymentMethod". The conflict occurred in database "DB_A28530_irit", table "dbo.PaymentMethod", column 'Id'.
The statement has been terminated.
--------------------------------------------------------------------------------------------
20210313 18:26:54 [33] ERROR Web [(null)] - StackTrace
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Suftnet.Cos.Extension.ViewExtensions.ToDate(String value) in E:\Git\Web\Irit\Irit\Suftnet.Cos\Extensions\ViewExtensions.cs:line 303
   at Suftnet.Cos.Web.Command.PaymentCommand.ResetTable() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Command\PaymentCommand.cs:line 40
   at Suftnet.Cos.Web.Command.PaymentCommand.Execute() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Command\PaymentCommand.cs:line 33
   at Suftnet.Cos.Mobile.PaymentController.<Create>b__3_0() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Controllers\Api\v1\PaymentController.cs:line 41
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Suftnet.Cos.Mobile.PaymentController.<Create>d__3.MoveNext() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Controllers\Api\v1\PaymentController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Suftnet.Cos.Web.ActionFilter.AddChallengeOnUnauthorizedResult.<ExecuteAsync>d__7.MoveNext() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Infrastructure\ActionFilter\AddChallengeOnUnauthorizedResult.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()Messages
String was not recognized as a valid DateTime.
--------------------------------------------
Request.Body = {"amountPaid":52.98,"createdDt":"3/13/2021 06:26:44","externalId":"115924fb-79f9-4e0c-ab5f-d4e1dfc1c893","grandTotal":52.980000000000004,"orderId":"a2bc3624-6fe9-44f0-8c27-024ed4af406c","paymentMethodId":"E0DF7037-BE71-4D90-871D-04AD8E4AD960","tableId":"2d7dcc2a-05e2-4363-bf22-ea7355d943d2","userName":"Abel James"}

--------------------------------------------------------------------------------------------
20210313 18:27:29 [33] ERROR Web [(null)] - StackTrace
   at System.DateTimeParse.Parse(String s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at Suftnet.Cos.Extension.ViewExtensions.ToDate(String value) in E:\Git\Web\Irit\Irit\Suftnet.Cos\Extensions\ViewExtensions.cs:line 303
   at Suftnet.Cos.Web.Command.PaymentCommand.ResetTable() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Command\PaymentCommand.cs:line 40
   at Suftnet.Cos.Web.Command.PaymentCommand.Execute() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Command\PaymentCommand.cs:line 33
   at Suftnet.Cos.Mobile.PaymentController.<Create>b__3_0() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Controllers\Api\v1\PaymentController.cs:line 41
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Suftnet.Cos.Mobile.PaymentController.<Create>d__3.MoveNext() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Controllers\Api\v1\PaymentController.cs:line 41
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Suftnet.Cos.Web.ActionFilter.AddChallengeOnUnauthorizedResult.<ExecuteAsync>d__7.MoveNext() in E:\Git\Web\Irit\Irit\Suftnet.Cos\Infrastructure\ActionFilter\AddChallengeOnUnauthorizedResult.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.AuthenticationFilterResult.<ExecuteAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()Messages
String was not recognized as a valid DateTime.
--------------------------------------------
Request.Body = {"amountPaid":52.98,"createdDt":"3/13/2021 06:27:01","externalId":"115924fb-79f9-4e0c-ab5f-d4e1dfc1c893","grandTotal":52.980000000000004,"orderId":"a2bc3624-6fe9-44f0-8c27-024ed4af406c","paymentMethodId":"E0DF7037-BE71-4D90-871D-04AD8E4AD960","tableId":"2d7dcc2a-05e2-4363-bf22-ea7355d943d2","userName":"Abel James"}

--------------------------------------------------------------------------------------------
